### ISSUE TITLE
export_options.plist not found when using codemagic.yaml

### ISSUE THREAD

**Issue by SharbelOkzan** [codemagic-ci-cd/cli-tools#265]
I was using the Workflow Editor to build and deploy a Flutter project. Everything was fine and the workflow was publishing successfully both for Android and iOS. Then we decided to use codemagic.yaml instead of the Workflow Editor.

When switching, I checked the _Export current configuration as codemagic.yaml_ option and committed the generated codemagic.yaml to the repo. I expected that this file should be equivalent to the configurations I set in the UI. However I got the following error:
```
"~/export_options.plist" property list does not exist.


Build failed :|
Step 12 script `cd app && flutter build ipa --export-options-plist=~/export_options.plist --buil ...` exited with status code 1
```
as a result of executing this command:
```
#!/usr/bin/env bash

cd app && flutter build ipa --export-options-plist=~/export_options.plist --build-name=2.0.$PROJECT_BUILD_NUMBER --build-number=$PROJECT_BUILD_NUMBER --flavor stage -t lib/main/main_stage.dart
```
The command above was in the **generated codemagic.yaml** .
The `build-name`, `build_number`, `flavor` and `target` params were as per my Workflow Editor, but not the [export-options-list](https://docs.flutter.dev/deployment/ios#upload-the-app-bundle-to-app-store-connect), I didn't add that one.

I understand that `export_options.plist` is the output of `xcode-project use-profiles`. [By default](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/xcode-project/use-profiles.md#--export-options-plistexport_options_path), the previous command should generate the desired file in `$HOME/export_options.plist`. Which is the same as the path passed to `cd app && flutter build ipa --export-options-plist` above.

I echoed `$HOME` and got `/Users/builder` as expected.

Finally, I changed `--export-options-plist=~/export_options.plist` in the flutter build ipa command to `--export-options-plist=/Users/builder/export_options.plist` and it worked.

Here's the relevant part of generated `codemagic,yaml` file that I get from exporting the configurations of my Workflow Editor without any change. The same workflow was working fine.

```
workflows:
############################################################
########################## Stage ###########################
############################################################
  stage:
    name: stage
    max_build_duration: 60
    environment:
      vars:
        dummy_env: Encrypted( encryptedValue123....end)
        env: Encrypted( encryptedValue123....end)
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        FCI_KEYSTORE: Encrypted( encryptedValue123....end)
        FCI_KEYSTORE_PASSWORD: Encrypted( encryptedValue123....end)
        FCI_KEY_PASSWORD: Encrypted( encryptedValue123....end)
        FCI_KEY_ALIAS: Encrypted( encryptedValue123....end)
        APP_STORE_CONNECT_ISSUER_ID: cXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX7
        APP_STORE_CONNECT_KEY_IDENTIFIER: BXXXXXXXX9
        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted( encryptedValue123....end)
        CERTIFICATE_PRIVATE_KEY: Encrypted( encryptedValue123....end)
      flutter: default
      xcode: latest
      cocoapods: default
    cache:
      cache_paths: []
    scripts:
      - |
        # set up key.properties
        echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
        cat >> "$FCI_BUILD_DIR/app/android/key.properties" <<EOF
        storePassword=$FCI_KEYSTORE_PASSWORD
        keyPassword=$FCI_KEY_PASSWORD
        keyAlias=$FCI_KEY_ALIAS
        storeFile=/tmp/keystore.keystore
        EOF
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/app/android/local.properties"
      - cd app && flutter packages pub get
      - | 
        #the next two lines are to set our dummy_env values as codemagic env variables
        echo $dummy_env | base64 --decode > app/.env
        grep -v -e '^[[:space:]]*$' app/.env | grep -v '^#' >> $CM_ENV
      - cd app && flutter build appbundle --release --build-name=2.0.$PROJECT_BUILD_NUMBER
        --build-number=$PROJECT_BUILD_NUMBER --flavor stage -t lib/main/main_stage.dart
      - find . -name "Podfile" -execdir pod install \;
      - keychain initialize
      - app-store-connect fetch-signing-files "com.company.appname.stage" --type
        IOS_APP_STORE --create
      - keychain add-certificates
      # I think the next two commands are what's relavent to this issue
      - xcode-project use-profiles
      - cd app && flutter build ipa --export-options-plist=~/export_options.plist
        --build-name=2.0.$PROJECT_BUILD_NUMBER --build-number=$PROJECT_BUILD_NUMBER
        --flavor stage -t lib/main/main_stage.dart
      - echo $PROJECT_BUILD_NUMBER
    artifacts:
      - app/build/**/outputs/apk/**/*.apk
      - app/build/**/outputs/bundle/**/*.aab
      - app/build/**/outputs/**/mapping.txt
      - app/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - app/*.snap
      - app/build/windows/**/*.msix
      - app/flutter_drive.log
    publishing:
      email:
        recipients:
          - development@company.pl
      google_play:
        credentials: Encrypted( encryptedValue123....end)
        track: internal
        in_app_update_priority: 0
      app_store_connect:
        api_key: Encrypted( encryptedValue123....end)
        key_id: BXXXXXXXX9
        issuer_id: cXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXX7
        submit_to_testflight: true
        submit_to_app_store: false
        
############################################################
########################## Prod ############################
############################################################

  prod:
    name: prod
    max_build_duration: 60
    environment:
    ## ...........
    ## ...........
    ## ...........
```

Am I doing something wrong? or the default output path of `xcode-project use-profiles` needs to be fixed?
